<a href="https://colab.research.google.com/github/ramankgp/30DaysOfFlutter/blob/day1/MTP_significant_variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('proj.csv')
x1 = df.drop(columns=["Sr_NO","Lat","Lon","EC","Block","Location"])
y2 = df["EC"]

In [ ]:
y1=(y2>1500)*1.0

In [ ]:
#df.head()

In [ ]:
X_lithology=pd.get_dummies(x1['Lithology'])
U=pd.concat([x1.drop(columns=["Lithology"]),X_lithology],axis=1)

In [ ]:
X_hydcond=pd.get_dummies(x1['Hyd_cond'])
U2=pd.concat([U.drop(columns=["Hyd_cond"]),X_hydcond],axis=1)

In [ ]:
len(U2.columns)

33

In [ ]:
U2=U2.rename(columns={U2.columns[27]: "a", U2.columns[28]: "b", U2.columns[29]: "c",U2.columns[30]: "d", U2.columns[31]: "e", U2.columns[32]: "f"})

In [ ]:
U2.columns

Index(['Pop_den', 'Precipi', 'ET', 'Aridity', 'Irr_gw', 'OC_sub', 'pH_sub',
       'cec_sub', 'silt_sub', 'sand_sub', 'lulc', 'twi', 'elevation',
       'Dist_coast_km', 'Dist_strm_km', 'mt', 'pa', 'pb', 'pi', 'sc', 'sm',
       'ss', 'su', 'va', 'vb', 'vi', 'wb', 'a', 'b', 'c', 'd', 'e', 'f'],
      dtype='object')

In [ ]:
X_lulc=pd.get_dummies(x1['lulc'])
U3=pd.concat([U2.drop(columns=["lulc"]),X_lulc],axis=1)

In [ ]:
len(U3.columns)

42

In [ ]:
U3=U3.rename(columns={U3.columns[32]: "a1", U3.columns[33]: "b1", U3.columns[34]: "c1", U3.columns[35]: "d1",U3.columns[36]: "e1", U3.columns[37]: "f1", U3.columns[38]: "g1", U3.columns[39]: "h1",U3.columns[40]: "i1",U3.columns[41]: "j1"})

In [ ]:
print(U3.columns)

Index(['Pop_den', 'Precipi', 'ET', 'Aridity', 'Irr_gw', 'OC_sub', 'pH_sub',
       'cec_sub', 'silt_sub', 'sand_sub', 'twi', 'elevation', 'Dist_coast_km',
       'Dist_strm_km', 'mt', 'pa', 'pb', 'pi', 'sc', 'sm', 'ss', 'su', 'va',
       'vb', 'vi', 'wb', 'a', 'b', 'c', 'd', 'e', 'f', 'a1', 'b1', 'c1', 'd1',
       'e1', 'f1', 'g1', 'h1', 'i1', 'j1'],
      dtype='object')


In [ ]:
newset=pd.concat([U3,y1],axis=1)
# newset.corr('spearman').sort_values(['EC'],ascending=False)['EC']

In [ ]:
newset.columns

Index(['Pop_den', 'Precipi', 'ET', 'Aridity', 'Irr_gw', 'OC_sub', 'pH_sub',
       'cec_sub', 'silt_sub', 'sand_sub', 'twi', 'elevation', 'Dist_coast_km',
       'Dist_strm_km', 'mt', 'pa', 'pb', 'pi', 'sc', 'sm', 'ss', 'su', 'va',
       'vb', 'vi', 'wb', 'a', 'b', 'c', 'd', 'e', 'f', 'a1', 'b1', 'c1', 'd1',
       'e1', 'f1', 'g1', 'h1', 'i1', 'j1', 'EC'],
      dtype='object')

In [ ]:
newset.isna().sum()

Pop_den          0
Precipi          0
ET               0
Aridity          0
Irr_gw           0
OC_sub           0
pH_sub           0
cec_sub          0
silt_sub         0
sand_sub         0
twi              0
elevation        0
Dist_coast_km    0
Dist_strm_km     0
mt               0
pa               0
pb               0
pi               0
sc               0
sm               0
ss               0
su               0
va               0
vb               0
vi               0
wb               0
a                0
b                0
c                0
d                0
e                0
f                0
a1               0
b1               0
c1               0
d1               0
e1               0
f1               0
g1               0
h1               0
i1               0
j1               0
EC               0
dtype: int64

In [ ]:
from scipy.stats import spearmanr
correlation, pval = spearmanr(newset)

In [ ]:
pd.DataFrame(correlation)[42]

0    -0.036388
1    -0.376068
2     0.323133
3    -0.395339
4     0.142957
5    -0.076489
6     0.336463
7     0.032309
8    -0.133847
9     0.146738
10    0.089828
11    0.026319
12   -0.007193
13   -0.039762
14    0.009905
15    0.009288
16    0.041940
17    0.009608
18    0.013853
19   -0.010176
20   -0.060487
21    0.006800
22    0.039051
23    0.011260
24   -0.018994
25   -0.011523
26   -0.022479
27   -0.072186
28   -0.000539
29    0.031697
30    0.004924
31    0.033685
32    0.000620
33    0.065450
34    0.050137
35   -0.090657
36   -0.061626
37   -0.007543
38   -0.006158
39    0.009608
40    0.042859
41   -0.009763
42    1.000000
Name: 42, dtype: float64

In [ ]:
pd.DataFrame(pval)[42]

0      3.821941e-05
1      0.000000e+00
2     7.006477e-309
3      0.000000e+00
4      2.012352e-59
5      4.478314e-18
6      0.000000e+00
7      2.561344e-04
8      3.006620e-52
9      1.525253e-62
10     2.364894e-24
11     2.901148e-03
12     4.157884e-01
13     6.793320e-06
14     2.624737e-01
15     2.933682e-01
16     2.067079e-06
17     2.770395e-01
18     1.170528e-01
19     2.496494e-01
20     7.429130e-12
21     4.417091e-01
22     9.888843e-06
23     2.026973e-01
24     3.163832e-02
25     1.923436e-01
26     1.097833e-02
27     2.908637e-16
28     9.513668e-01
29     3.348347e-04
30     5.774734e-01
31     1.379118e-04
32     9.441231e-01
33     1.240741e-13
34     1.381942e-08
35     8.925694e-25
36     2.985100e-12
37     3.934888e-01
38     4.859954e-01
39     2.770395e-01
40     1.229448e-06
41     2.693844e-01
42     0.000000e+00
Name: 42, dtype: float64

In [ ]:
 from sklearn.model_selection import train_test_split
 U_train, U_test, y_train, y_test = train_test_split(U3, y1, test_size=0.20, random_state=0)

In [ ]:
#U_train.head()

In [ ]:
#y_train

In [ ]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression(max_iter=10000,random_state=0)
clf.fit(U_train, y_train)
predicted = clf.predict(U_test)
predicted

array([0., 0., 0., ..., 0., 1., 0.])

In [ ]:
pd.DataFrame(clf.predict_proba(U_train))

0         1
0      0.922000  0.078000
1      0.485214  0.514786
2      0.988665  0.011335
3      0.968226  0.031774
4      0.616911  0.383089
...         ...       ...
10235  0.992287  0.007713
10236  0.932653  0.067347
10237  0.751846  0.248154
10238  0.901137  0.098863
10239  0.645474  0.354526

[10240 rows x 2 columns]

In [ ]:
pd.DataFrame(clf.coef_).transpose()

0
0   0.000024
1  -0.000431
2  -0.000742
3  -0.002190
4   0.003624
5   0.001922
6   0.082795
7  -0.021623
8  -0.106019
9  -0.008356
10  0.005588
11 -0.001394
12 -0.001118
13 -0.028263
14 -0.098519
15 -0.149456
16  0.073704
17  0.005047
18 -0.037117
19 -0.018729
20 -0.220035
21  0.269763
22  0.009849
23  0.060855
24 -0.010162
25 -0.004521
26  0.045120
27 -0.279100
28 -0.031449
29 -0.040859
30  0.111684
31  0.073862
32 -0.033394
33 -0.147330
34 -0.000777
35  0.085865
36  0.008552
37 -0.001037
38 -0.000329
39 -0.002209
40 -0.053173
41  0.023090

In [ ]:
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
model = sm.GLM.from_formula("EC ~ Pop_den + Precipi + ET + Aridity + Irr_gw + OC_sub + pH_sub + cec_sub + silt_sub+sand_sub +twi + elevation + Dist_coast_km + Dist_strm_km + mt+pa+pb+pi+sc+sm+ss+su+va+vb+vi+wb", family=sm.families.Binomial(), data=newset)
result = model.fit()
result.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results                  
==============================================================================
Dep. Variable:                     EC   No. Observations:                12801
Model:                            GLM   Df Residuals:                    12774
Model Family:                Binomial   Df Model:                           26
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -4983.0
Date:                Thu, 08 Apr 2021   Deviance:                       9966.1
Time:                        09:35:52   Pearson chi2:                 1.51e+04
No. Iterations:                    22                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept       -35.8346   4.55e+04     -0.001      0.999   -8.93e+04    8.92e+04
Pop_den        2.731e-05   9.12e-06      2.996      0.003    9.44e-06    4.52e-05
Precipi          -0.0013      0.000     -3.982      0.000      -0.002      -0.001
ET                0.0016      0.000      5.397      0.000       0.001       0.002
Aridity        1.708e-05      0.000      0.067      0.946      -0.000       0.001
Irr_gw            0.0021      0.001      2.236      0.025       0.000       0.004
OC_sub            0.0017      0.000      3.495      0.000       0.001       0.003
pH_sub            0.1249      0.008     15.679      0.000       0.109       0.141
cec_sub          -0.0078      0.005     -1.509      0.131      -0.018       0.002
silt_sub          0.0045      0.011      0.417      0.677      -0.017       0.026
sand_sub          0.0446      0.008      5.757      0.000       0.029       0.060
twi               0.0315      0.014      2.209      0.027       0.004       0.059
elevation        -0.0001      0.000     -0.721      0.471      -0.000       0.000
Dist_coast_km    -0.0018      0.000    -11.687      0.000      -0.002      -0.001
Dist_strm_km     -0.0172      0.011     -1.509      0.131      -0.040       0.005
mt               21.0927   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
pa               20.9777   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
pb               22.0919   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
pi               22.3914   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
sc               20.4929   4.55e+04      0.000      1.000   -8.93e+04    8.93e+04
sm               20.9892   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
ss               20.6174   4.55e+04      0.000      1.000   -8.93e+04    8.93e+04
su               21.1797   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
va               21.1851   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
vb               20.8977   4.55e+04      0.000      1.000   -8.92e+04    8.93e+04
vi                0.1893   4.89e+04   3.87e-06      1.000   -9.58e+04    9.58e+04
wb                0.0865   5.41e+04    1.6e-06      1.000   -1.06e+05    1.06e+05
=================================================================================
"""

+a+b+c+d+e+f+a1+b1+c1+d1+e1+f1+g1+h1+i1+j1

In [ ]:
importance = clf.coef_[0]
# summarize feature importance
for i,v in enumerate(importance):
	#print('Feature: %0d, Score: %.5f' % (i,v))
  print('%.5f' % (v))

0.00002
-0.00043
-0.00074
-0.00219
0.00362
0.00192
0.08279
-0.02162
-0.10602
-0.00836
0.00559
-0.00139
-0.00112
-0.02826
-0.09852
-0.14946
0.07370
0.00505
-0.03712
-0.01873
-0.22003
0.26976
0.00985
0.06086
-0.01016
-0.00452
0.04512
-0.27910
-0.03145
-0.04086
0.11168
0.07386
-0.03339
-0.14733
-0.00078
0.08587
0.00855
-0.00104
-0.00033
-0.00221
-0.05317
0.02309


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.8098399062866068

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 1000, max_depth= 2, random_state=0)
clf.fit(U_train, y_train)
predicted = clf.predict(U_test)
predicted

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predicted)

0.8012495119094104

dividing data into bins
K=1+3.322logN
K=15bins

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
#classification_report(y_test, predicted)
print(classification_report(y_test,predicted))
print(confusion_matrix(y_test,predicted))

              precision    recall  f1-score   support

         0.0       0.80      1.00      0.89      2052
         1.0       0.00      0.00      0.00       509

    accuracy                           0.80      2561
   macro avg       0.40      0.50      0.44      2561
weighted avg       0.64      0.80      0.71      2561

[[2052    0]
 [ 509    0]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
